// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJkCQRrHbVS3TaCamV_UyBhB9UgUSwtw',
    appId: '1:598719317195:web:7c2c2ba640f717922d874e',
    messagingSenderId: '598719317195',
    projectId: 'proyecto-final-6cbdd',
    authDomain: 'proyecto-final-6cbdd.firebaseapp.com',
    storageBucket: 'proyecto-final-6cbdd.firebasestorage.app',
    measurementId: 'G-3L78LGBSR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgriUODE1kCJ08cb8DivWsxImEcFnRi6o',
    appId: '1:598719317195:android:eb40c6ea56dfd6ac2d874e',
    messagingSenderId: '598719317195',
    projectId: 'proyecto-final-6cbdd',
    storageBucket: 'proyecto-final-6cbdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArmwVkiEK_fcSiCTmR8V2kxnjxiTYDKa8',
    appId: '1:598719317195:ios:99983380844776832d874e',
    messagingSenderId: '598719317195',
    projectId: 'proyecto-final-6cbdd',
    storageBucket: 'proyecto-final-6cbdd.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArmwVkiEK_fcSiCTmR8V2kxnjxiTYDKa8',
    appId: '1:598719317195:ios:99983380844776832d874e',
    messagingSenderId: '598719317195',
    projectId: 'proyecto-final-6cbdd',
    storageBucket: 'proyecto-final-6cbdd.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJkCQRrHbVS3TaCamV_UyBhB9UgUSwtw',
    appId: '1:598719317195:web:226fbbb691ddd5c82d874e',
    messagingSenderId: '598719317195',
    projectId: 'proyecto-final-6cbdd',
    authDomain: 'proyecto-final-6cbdd.firebaseapp.com',
    storageBucket: 'proyecto-final-6cbdd.firebasestorage.app',
    measurementId: 'G-0Y7F209N5E',
  );
}
